/** 应用组合层的公开入口，领域代码不得反向依赖这里的具体组件实现。 */
export * from './AppGlobalOverlays'
export * from './AppRepositoryOverlays'
export * from './AppShell'
export * from './AppWorkspace'
export * from './appUpdater'
export * from './createPlaceholderRepository'
export * from './components/SearchDialog'
export * from './components/SettingsDialog'
export * from './components/Sidebar'
export * from './components/UpdateDialog'
export * from './useAppOverlayState'
export * from './useAppFeedback'
export * from './useAppToolbarActions'
export * from './useAppWorkspaceNavigation'
export * from './useAppVersionActions'
